baseURL = "https://fabiogeraci.github.io/"
languageCode = 'en-us'
title = 'mljourney'
theme='m10c'
enableEmoji = true
[params]
title = "My Journey into ML/AI"
author = "Fabio Geraci"
description = "Fabio Geraci's personal website"
